image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - aaron-bond.better-comments
    - bierner.markdown-mermaid
    - denoland.vscode-deno
    - esbenp.prettier-vscode
    - humao.rest-client
    - sastan.twind-intellisense
