// Install the following VS Code extension to use:
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# ? ----------------------------------------------------------------------------
# ? Modify the following variables before running your requests:
# ? ----------------------------------------------------------------------------

@baseUrl = https://reel-deal.napjose.ph
@contentType = application/json
@userName = John Doe
@userEmail = john.doe@example.com
@userPassword = My-Password-1234

################################################################################
# @name createUser
# TITLE: Register
# DESCRIPTION: Creates a new User using the provided credentials.
# EXAMPLE RESPONSE:
# {
#   "id": "01HB306BDTMDFERZ04Q6S94B9N",
#   "name": "John Doe"
# }
POST {{baseUrl}}/api/users
Content-Type: {{contentType}}

{
  "name": "{{userName}}",
  "email": "{{userEmail}}",
  "password": "{{userPassword}}"
}

################################################################################
# @name loginUser
# TITLE: Login
# DESCRIPTION: Logs in using the provided credentials and returns the access and refresh tokens.
# EXAMPLE RESPONSE:
# {
#   "user": {
#     "id": "01HB306BDTMDFERZ04Q6S94B9N",
#     "name": "John Doe"
#   },
#   "tokens": {
#     "access": {
#       "type": "access_token",
#       "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJyZWVsLWRlYWwiLCJpYXQiOjE2OTU1Mzk0NzY5NTgsInN1YiI6IjAxSEIzMDZCRFRNREZFUlowNFE2Uzk0QjlOIiwiZXhwIjoxNjk1NTQzMDc2OTU4fQ.URgyU23XWru2UQMQzXqAiffpW55SBPjwctlF9p82PFdzThL5RYq1C8-ykIQCxexoZqORNF1zBdVKlX2LTNpYtw",
#       "expires": "2023-09-24T08:11:16.958Z"
#     },
#     "refresh": {
#       "type": "refresh_token",
#       "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJyZWVsLWRlYWwiLCJpYXQiOjE2OTU1Mzk0NzY5NjAsInN1YiI6IjAxSEIzMDZCRFRNREZFUlowNFE2Uzk0QjlOIiwiZXhwIjoxNjk1NTQxMjc2OTU4fQ.HEPm4QSXdzEBsaOyPVyECoC-Vs9CSQEMqA4Xc2wNUNtezIe9XDI7G_APwpbUKpkB2lwN-Al80oQkcLT0OKtYgg",
#       "expires": "2023-09-24T07:41:16.958Z"
#     }
#   }
# }
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "{{userEmail}}",
  "password": "{{userPassword}}"
}

################################################################################
# @name getUsers
# TITLE: List Users
# DESCRIPTION: Lists all the available public information of Users.
# EXAMPLE RESPONSE:
# {
#   "results": [
#     {
#       "id": "01HB0ZQET8Q8CG8131VW7JP2AY",
#       "name": "Rob Banks"
#     },
#     {
#       "id": "01HB306BDTMDFERZ04Q6S94B9N",
#       "name": "John Doe"
#     }
#   ],
#   "count": 2,
#   "limit": 25,
#   "reverse": false,
#   "cursor": ""
# }
GET {{baseUrl}}/api/users
Content-Type: {{contentType}}

################################################################################
# @name getUsersWithQueryParams
# TITLE: List Users Parameterized
# DESCRIPTION: Lists all the available public information of Users, with query parameters.
# EXAMPLE RESPONSE:
# {
#   "results": [
#     {
#       "id": "01HB0ZQET8Q8CG8131VW7JP2AY",
#       "name": "Rob Banks"
#     }
#   ],
#   "count": 2,
#   "limit": 1,
#   "reverse": true,
#   "cursor": "AjAxSEIwWlFFVDhROENHODEzMVZXN0pQMkFZAA=="
# }
GET {{baseUrl}}/api/users
  ?limit=1
  &reverse=true
Content-Type: {{contentType}}

################################################################################
# @name getUser
# TITLE: Get User
# DESCRIPTION: Gets the available public information of a specific User.
# EXAMPLE RESPONSE:
# {
#   "id": "01HB306BDTMDFERZ04Q6S94B9N",
#   "name": "John Doe"
# }
GET {{baseUrl}}/api/users/{{loginUser.response.body.$.user.id}}
Content-Type: {{contentType}}

################################################################################
# @name getMovies
# TITLE: List Movies
# DESCRIPTION: Lists all the available public information of Movies.
# EXAMPLE RESPONSE:
# {
#   "results": [
#     {
#       "id": "01HB3CJFJ6AD9HARTEDZKK7DTS",
#       "title": "On the Job",
#       "genre": [
#         "Action",
#         "Crime",
#         "Drama",
#         "Thriller"
#       ],
#       "releaseYear": 2021,
#       "rentalPrice": 100,
#       "availableCopies": 2
#     },
#     {
#       "id": "01HB3CJFJ6KZDAHRGTC27AKHP1",
#       "title": "Heneral Luna",
#       "genre": [
#         "Action",
#         "Biography",
#         "History",
#         "War"
#       ],
#       "releaseYear": 2015,
#       "rentalPrice": 100,
#       "availableCopies": 7
#     },
#     {
#       "id": "01HB3CJFJ72FEBQNVN6T96TQ8M",
#       "title": "Metro Manila",
#       "genre": [
#         "Crime",
#         "Drama"
#       ],
#       "releaseYear": 2013,
#       "rentalPrice": 100,
#       "availableCopies": 5
#     }
#   ],
#   "count": 3,
#   "limit": 25,
#   "reverse": false,
#   "cursor": ""
# }
GET {{baseUrl}}/api/movies
Content-Type: {{contentType}}

################################################################################
# @name getMoviesWithQueryParams
# TITLE: List Movies Parameterized
# DESCRIPTION: Lists all the available public information of Movies, with query parameters.
# EXAMPLE RESPONSE:
# {
#   "results": [
#     {
#       "id": "01HB3CJFJ6KZDAHRGTC27AKHP1",
#       "title": "Heneral Luna",
#       "genre": [
#         "Action",
#         "Biography",
#         "History",
#         "War"
#       ],
#       "releaseYear": 2015,
#       "rentalPrice": 100,
#       "availableCopies": 7
#     }
#   ],
#   "count": 3,
#   "limit": 25,
#   "reverse": false,
#   "cursor": "AjAxSEIzQ0pGSjZBRDlIQVJURURaS0s3RFRTAA=="
# }
GET {{baseUrl}}/api/movies
  ?limit=1
  &reverse=false
Content-Type: {{contentType}}

################################################################################
# @name getMovie
# TITLE: Get Movie
# DESCRIPTION: Gets the available public information of a specific Movie.
# EXAMPLE RESPONSE:
# {
#   "id": "01HB3CJFJ6KZDAHRGTC27AKHP1",
#   "title": "Heneral Luna",
#   "genre": [
#     "Action",
#     "Biography",
#     "History",
#     "War"
#   ],
#   "releaseYear": 2015,
#   "rentalPrice": 100,
#   "availableCopies": 7
# }
GET {{baseUrl}}/api/movies/{{getMovies.response.body.$.results[1].id}}
Content-Type: {{contentType}}

################################################################################
# @name createRental
# TITLE: Create Rental
# DESCRIPTION: Create a new Rental by the User.
# EXAMPLE RESPONSE:
# {
#   "id": "01HB3SF4KNZR0Y6GSDKG45NWHE",
#   "userId": "01HB306BDTMDFERZ04Q6S94B9N",
#   "movieId": "01HB3CJFJ6KZDAHRGTC27AKHP1",
#   "rentalDate": "2023-09-24T14:28:34.037Z",
#   "dueDate": "2023-10-01T14:28:34.037Z"
# }
POST {{baseUrl}}/api/rentals
Content-Type: {{contentType}}
Authorization: Bearer {{loginUser.response.body.$.tokens.access.token}}

{
  "userId": "{{loginUser.response.body.$.user.id}}",
  "movieId": "{{getMovies.response.body.$.results[1].id}}"
}

################################################################################
# @name getRentals
# TITLE: List Rentals
# DESCRIPTION: Lists all the available information of Rentals by the User.
# EXAMPLE RESPONSE:
# {
#   "results": [
#     {
#       "id": "01HB3SF4KNZR0Y6GSDKG45NWHE",
#       "userId": "01HB306BDTMDFERZ04Q6S94B9N",
#       "movieId": "01HB3CJFJ6KZDAHRGTC27AKHP1",
#       "rentalDate": "2023-09-24T14:28:34.037Z",
#       "dueDate": "2023-10-01T14:28:34.037Z"
#     }
#   ],
#   "count": 1,
#   "limit": 25,
#   "reverse": false,
#   "cursor": ""
# }
GET {{baseUrl}}/api/rentals
Content-Type: {{contentType}}
Authorization: Bearer {{loginUser.response.body.$.tokens.access.token}}

################################################################################
# @name getPreviousMovie
# TITLE: Get Previous Movie
# DESCRIPTION: Check the available copies of the previous movie.
# EXAMPLE RESPONSE:
# {
#   "id": "01HB3CJFJ6KZDAHRGTC27AKHP1",
#   "title": "Heneral Luna",
#   "genre": [
#     "Action",
#     "Biography",
#     "History",
#     "War"
#   ],
#   "releaseYear": 2015,
#   "rentalPrice": 100,
#   "availableCopies": 6
# }
GET {{baseUrl}}/api/movies/{{getMovies.response.body.$.results[1].id}}
Content-Type: {{contentType}}

################################################################################
# @name getRental
# TITLE: Get Rental
# DESCRIPTION: Gets the available information of a Rental by a specific User.
# EXAMPLE RESPONSE:
# {
#   "id": "01HB3SF4KNZR0Y6GSDKG45NWHE",
#   "userId": "01HB306BDTMDFERZ04Q6S94B9N",
#   "movieId": "01HB3CJFJ6KZDAHRGTC27AKHP1",
#   "rentalDate": "2023-09-24T14:28:34.037Z",
#   "dueDate": "2023-10-01T14:28:34.037Z",
#   "isReturned": false
# }
GET {{baseUrl}}/api/rentals/{{createRental.response.body.$.id}}
Content-Type: {{contentType}}
Authorization: Bearer {{loginUser.response.body.$.tokens.access.token}}

################################################################################
# @name removeRental
# TITLE: Remove Rental
# DESCRIPTION: Returns the Rental by a specific User.
# EXAMPLE RESPONSE:
# {
#   "userId": "01HB306BDTMDFERZ04Q6S94B9N",
#   "movieId": "01HB3CJFJ6KZDAHRGTC27AKHP1",
#   "id": "01HB3SF4KNZR0Y6GSDKG45NWHE",
#   "createdAt": "2023-09-24T14:28:34.037Z",
#   "rentalDate": "2023-09-24T14:28:34.037Z",
#   "dueDate": "2023-10-01T14:28:34.037Z",
#   "isReturned": true,
#   "returnedDate": "2023-09-24T15:52:58.089Z"
# }
DELETE {{baseUrl}}/api/rentals/{{createRental.response.body.$.id}}
Content-Type: {{contentType}}
Authorization: Bearer {{loginUser.response.body.$.tokens.access.token}}

################################################################################

# ! ONLY FOR DEBUGGING PURPOSES. POPULATE `xDebugModeKey` WITH THE VALUE OF THE
# ! CORRECT KEY BEFORE RUNNING THE REQUESTS.
# ! ----------------------------------------------------------------------------

@xDebugModeKey =

################################################################################
# @name deleteAllRentals
# TITLE: Delete Rentals
# DESCRIPTION: Deletes all the Rentals.
DELETE {{baseUrl}}/api/rentals
Content-Type: {{contentType}}
Authorization: Bearer {{loginUser.response.body.$.tokens.access.token}}
X-Debug-Mode: true
X-Debug-Mode-Key: {{xDebugModeKey}}

################################################################################
# @name deleteAllMovies
# TITLE: Delete Movies
# DESCRIPTION: Deletes all the Movies.
DELETE {{baseUrl}}/api/movies
Content-Type: {{contentType}}
Authorization: Bearer {{loginUser.response.body.$.tokens.access.token}}
X-Debug-Mode: true
X-Debug-Mode-Key: {{xDebugModeKey}}

################################################################################
# @name deleteAllUsers
# TITLE: Delete Users
# DESCRIPTION: Deletes all the Users.
DELETE {{baseUrl}}/api/users
Content-Type: {{contentType}}
Authorization: Bearer {{loginUser.response.body.$.tokens.access.token}}
X-Debug-Mode: true
X-Debug-Mode-Key: {{xDebugModeKey}}

################################################################################
# @name deleteAllTokens
# TITLE: Delete Tokens
# DESCRIPTION: Deletes all the Tokens.
DELETE {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}
Authorization: Bearer {{loginUser.response.body.$.tokens.access.token}}
X-Debug-Mode: true
X-Debug-Mode-Key: {{xDebugModeKey}}
